In [ ]:
import numpy
import math
#Método full
# print(numpy.full((3,3), 10.0))
# numpy.full((3,4) = Define as colunas e linhas, primeiro valor linhas. Segundo valor colunas
# Após a definição eu coloco o valor que quero receber, nesse caso 10.


M1 = numpy.array([[1,2,3], [4,5,6]])
M2 = numpy.array([[6,7,8], [3,2,1]])

print(((M1 * 2) / 2 ) * 3)
print("Media Matrizes")
mediaMatrizes = (M1 + M2) / 2
print(mediaMatrizes)





[[ 3.  6.  9.]
 [12. 15. 18.]]
Media Matrizes
[[3.5 4.5 5.5]
 [3.5 3.5 3.5]]


In [ ]:
import pandas as pd
#Criei o dicionario vazio
dados = {}
# Atribui ao meu dicionario dados coloquei uma lista de nomes e atribui a eles
dados ["nomes"] = ["Maria", "Jose", " Lucas"]
# Fiz a mesma coisa com idades, para atribuir via sequencia
dados ["Idades"] = [20,30,50]

# print(dados)

# Crio um data frame para atribuir os dados do meu dicionario e deixar em fomato
# de DataFrame
pd.DataFrame(dados)

# nomes = dados["nomes"]
# idades = dados["Idades"]

# jose = nomes[0]
# idadeJose = idades[0]
# print(jose)
# print(idadeJose)

df = pd.DataFrame(dados)
print(df.to_string())




    nomes  Idades
0   Maria      20
1    Jose      30
2   Lucas      50


Introdução ao Python

In [ ]:

def mais_um_ano(idade):
  return idade +1
mais_um_ano(20)


21

In [ ]:
filme1 = "Toy story 3"
filme2 = "Xuxa contra o baixo astral"
filme3 = "A volta dos que nao foram"

In [ ]:

filmes = ["Toy story 3", "Xuxa contra o baixo astral", "A volta dos que nao foram"]
filmes

['Toy story 3', 'Xuxa contra o baixo astral', 'A volta dos que nao foram']

In [ ]:
def imprimir_filmes(filmes_que_quero_imprimir):
  print("A listas de Filmes que tenho disponiveis é: ")
  print(filmes_que_quero_imprimir)

In [ ]:
imprimir_filmes(filmes)

A listas de Filmes que tenho disponiveis é: 
['Toy story 3', 'Xuxa contra o baixo astral', 'A volta dos que nao foram']


In [ ]:
filmes[0]

'Toy story 3'

In [ ]:
filmes[-1]
#pegando o ultimo elemento

'A volta dos que nao foram'

In [ ]:
filmes[1:]
#pegar da posição 1 pra frente


['Xuxa contra o baixo astral', 'A volta dos que nao foram']

In [ ]:
for filme in filmes:
  print(filme)

Toy story 3
Xuxa contra o baixo astral
A volta dos que nao foram


In [ ]:
def imprimir_filmes(filmes_impresso):
  print("A lista de filmes disponiveis são: ")
  for filme in filmes_impresso:
    print(filme)

In [ ]:
imprimir_filmes(filmes)

A lista de filmes disponiveis são: 
Toy story 3
Xuxa contra o baixo astral
A volta dos que nao foram


In [ ]:
# Dicionario
dados = {
    "nome" : "Guilherme",
    "Idade" : 30,
    "empresa" : "Google"
}

In [ ]:
dados

{'nome': 'Guilherme', 'Idade': 30, 'empresa': 'Google'}